/**
 * This file contains a blocklist of names for whom profile creation is forbidden.
 * Names should be in lowercase and normalized (no accents) for consistent checking.
 */
export const BLOCKED_NAMES: string[] = [
    'adolf hitler',
    'iosif stalin',
    'joe biden',
    'donald trump',
    'xi jinping',
    'vladimir putin',
    'emmanuel macron',
    'olaf scholz',
    'justin trudeau',
    'rishi sunak',
    'fumio kishida',
    'lula da silva',
    'gustavo petro',
    'gabriel boric',
    'andres manuel lopez obrador',
    'nayib bukele',
    'javier milei',
    'antonio guterres',
    'christine lagarde',
    'tedros adhanom',
    'jens stoltenberg',
    'janet yellen',
    'papa francisco',
    'dalai lama',
    'arzobispo de canterbury',
    'lider supremo',
    'elon musk',
    'mark zuckerberg',
    'tim cook',
    'satya nadella',
    'jeff bezos',
    'sundar pichai',
    'jamie dimon',
    'larry fink',
    'bill gates',
    'reina isabel ii',
    'nelson mandela',
    'barack obama',
    'george w. bush',
    'abraham lincoln',
    'benito mussolini',
    'fidel castro',
    'hugo chavez',
    'che guevara',
    'madre teresa',
    'martin luther king jr.',


    // Add other controversial names here in lowercase and without accents.
    // e.g., 'osama bin laden',
];
