/**
 * This file contains a blocklist of names for whom profile creation is forbidden.
 * Names should be in lowercase and normalized (no accents) for consistent checking.
 */
export const BLOCKED_NAMES: string[] = [
    'adolf hitler',
    'iosif stalin',
    'joe biden',
    'donald trump',
    'xi jinping',
    'vladimir putin',
    'emmanuel macron',
    'olaf scholz',
    'justin trudeau',
    'rishi sunak',
    'fumio kishida',
    'lula da silva',
    'gustavo petro',
    'gabriel boric',
    'andres manuel lopez obrador',
    'nayib bukele',
    'javier milei',
    'antonio guterres',
    'christine lagarde',
    'tedros adhanom',
    'jens stoltenberg',
    'janet yellen',
    'papa francisco',
    'dalai lama',
    'arzobispo de canterbury',
    'lider supremo',
    'elon musk',
    'mark zuckerberg',
    'tim cook',
    'satya nadella',
    'jeff bezos',
    'sundar pichai',
    'jamie dimon',
    'larry fink',
    'bill gates',
    'reina isabel ii',
    'nelson mandela',
    'barack obama',
    'george w. bush',
    'abraham lincoln',
    'benito mussolini',
    'fidel castro',
    'hugo chavez',
    'che guevara',
    'madre teresa',
    'martin luther king jr.',
    'george soros',
    'klaus schwab',
    'bill clinton',
    'hillary clinton',
    'angela merkel',
    'benjamin netanyahu',
    'recep tayyip erdogan',
    'principe carlos (rey carlos iii)',
    'principe guillermo',
    'david rockefeller',
    'warren buffett',
    'michael bloomberg',
    'oprah winfrey',
    'rupert murdoch',
    'jeff williams (apple)',
    'susan wojcicki (ex-youtube)',
    'reed hastings (netflix)',
    'bernard arnault (lvmh)',
    'mukesh ambani',
    'jack ma (alibaba)',
    'wang jianlin',
    'mark carney',
    'jerome powell (reserva federal)',
    'christine wormuth',
    'gina raimondo',
    'anthony blinken',
    'nancy pelosi',
    'chuck schumer',
    'mitch mcconnell',
    'alexandria ocasio-cortez',
    'bernie sanders',
    'joe manchin',
    'amy coney barrett (jueza)',
    'sonia sotomayor (jueza)',
    'john roberts (juez)',
    'stephen breyer (juez)',
    'ted cruz',
    'john f. kennedy (jfk)',
    'martin luther',
    'vladimir lenin',
    'mao zedong',
    'mahatma gandhi',
    'winston churchill',
    'franklin d. roosevelt',
    'rey felipe vi',
    'isabel diaz ayuso',
    'andres pastrana',
    'sebastian pinera',
    'ricardo martinelli',
    'dilma rousseff',
    'nelson rockefeller',
    'john d. rockefeller',
    'jacob rothschild',
    'nathan rothschild',
    'familia rockefeller',
    'familia rothschild',
    'familia warburg',
    'familia morgan',
    'familia vanderbilt',
    'henry kissinger',
    'jeffrey epstein',
    'ghislaine maxwell',
    'george bush sr.',
    'george bush jr.',
    'dick cheney',
    'al gore',
    'tony blair',
    'nicolas sarkozy',
    'shinzo abe',
    // Add other controversial names here in lowercase and without accents.
    // e.g., 'osama bin laden',
];
